
export const NEWS_ITEM_EXPIRE_DAYS = 30;
export const NEWS_EVENT_EXPIRE_DAYS = 366 * 5;
export const NEWS_EVENT_TOPIC_EXPIRE_DAYS = 366;
export const NEWS_MAX_SUMMARY_LENGTH = 250;
export const NEWS_MIN_SUMMARY_LENGTH = 100;
